# Generated by Django 5.0.2 on 2024-05-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(blank=True, default='Unknown', max_length=256, null=True),
        ),
    ]
