# Generated by Django 5.0.2 on 2024-05-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='writer',
            field=models.CharField(blank=True, default='Admin', max_length=256, null=True),
        ),
    ]
