# Generated by Django 5.0.2 on 2024-05-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_writer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-date_posted',)},
        ),
        migrations.AddField(
            model_name='blog',
            name='image2',
            field=models.ImageField(blank=True, default='images/default_image.jpg', max_length=255, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image3',
            field=models.ImageField(blank=True, default='images/default_image.jpg', max_length=255, null=True, upload_to='images/'),
        ),
    ]
