# Generated by Django 5.0.2 on 2024-05-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
