# Generated by Django 5.0.2 on 2024-05-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0006_delete_presentations_delete_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='zlide',
            name='presentation_name',
            field=models.CharField(blank=True, default='Untitled Presentation', max_length=256, null=True),
        ),
    ]
