# Generated by Django 5.0.2 on 2024-05-24 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0007_zlide_presentation_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zlide',
            options={'ordering': ('-created_at',)},
        ),
    ]
